# Generated by Django 5.0.4 on 2024-04-21 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RatingReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_reg', models.IntegerField()),
                ('c_name', models.CharField(max_length=100)),
                ('s_ratings', models.IntegerField()),
                ('s_reviews', models.TextField()),
            ],
        ),
    ]
