# Generated by Django 5.0.4 on 2024-04-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='c_img',
            field=models.ImageField(upload_to='media/static/courses_pic'),
        ),
    ]
